### ISSUE TITLE
Would it be possible to distribute the StockPlusController.cfg in a .zip?

### ISSUE THREAD

**Issue by Dazpoet** [ClawKSP/KSP-Stock-Bug-Fix-Modules#2]
Hello!

I'm one of the people maintaining CKAN metadata over at https://github.com/KSP-CKAN and we recentlyn recieved https://github.com/KSP-CKAN/CKAN-meta/issues/572 about adding the .cfg for StockPlus to our metadata to enable users to download it through CKAN.

At this time, and for a forseeable future, we can only index things from inside .zip archives so I wonder if it would be possible to add a .zip with the .cfg file to your releases? It would be greatly appreciated by our users and help us out :)

//Daz

**Comment by ClawKSP** [comment]
Fixed
