### ISSUE TITLE
Breaks KIS

### ISSUE THREAD

**Issue by mblob** [ClawKSP/KSP-Stock-Bug-Fix-Modules#6]
After installing your mod.

First it worked perfectly. Temp on my station returned to normal.
But ...

Lots of "[Exception]: NullReferenceException: Object reference not set to an instance of an object" in debug console.

Kerbal's inventories (KIS mod) are not accesible anymore (no more menu entry on right clic on the kerbal or the vessel). 
![kerbal_1](https://cloud.githubusercontent.com/assets/967684/9443627/5d1188f0-4a82-11e5-988e-0592f8cabe0e.jpg)

When moving kerbal close to inventory capable part and right clicking inventory menu entry on the part, inventory window pops up then disapear. 

Kerbal inventories are clearly destroyed. Even after uninstalling KSP-Stock-Bug-Fix-Modules kerbals inventories are still not accessible.

I had some messages about ship not loading because of missing part longantenna.

Hopefully i'am using the S.A.V.E mod.

I have a heavy suspicion about the overheatfix (reason why i downloaded your mod), which worked perfectly.

Here is an extrait of my persistent.sfs file with data related to my station.
http://dl.free.fr/qw5lBFGjk

**Comment by ClawKSP** [comment]
Well, do you happen to have a log file? I don't expect OverheatFix to be involved here, but there are other fixes which might be interfering. If all you need is the OverheatFix, you can delete everything else and keep just that directory. If it still does it, that narrows it down.

**Comment by ClawKSP** [comment]
Rendered obsolete by release of KSP v1.0.5.
